### ISSUE TITLE
Got error with postgresql

### ISSUE THREAD

**Issue by lukebaze** [pss2138/django_ebay_scrapy#1]
Hello, thank you for the great project. 
However, i got this error, can you help me define how to debug it
![image](https://user-images.githubusercontent.com/67284748/95171607-5aa89b00-07e0-11eb-83e2-6a62d941966b.png)

**Comment by pss2138** [comment]
Hey there!

I'm glad you are working with Django eBay Scrapy. 
It looks like you made the postgre db and migrations well. 
I think you may need to touch ebay_scrapy/urls.py part.
It said "no relations", which means that requesting the data and the table that you made is not matching. 
Please try to look if you are matching the data request with the db table well:)
I'm open to more questions, if needed!

Happy coding :D
-Shawnpy

**Comment by lukebaze** [comment]
Thank you for your answer and also the great project 👍  How can i crawl the data if this keyword (a.k.a) items has many solds per month or not? Do you recommend any project?

**Comment by lukebaze** [comment]
> Hey there! I'm glad you are working with Django eBay Scrapy. It looks like you made the postgre db and migrations well. I think you may need to touch ebay_scrapy/urls.py part. It said "no relations", which means that requesting the data and the table that you made is not matching. Please try to look if you are matching the data request with the db table well:) I'm open to more questions, if needed! Happy coding :D -Shawnpy
> […](#)
> On Oct 6, 2020, at 4:29 PM, hiehoo ***@***.***> wrote: ﻿ Hello, thank you for the great project. However, i got this error, can you help me define how to debug it — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

After a day of finding way to correct the DB, I can use it properly, thanks for your help. It's showed that i need to insert the Counts column in the table_category table.... 
![Screenshot_20201009_105605](https://user-images.githubusercontent.com/67284748/95541782-5f5a9280-0a1e-11eb-9171-f31a801a79c8.png)
